feat: redis key helper
forkyid/go-utils pull request #19
Opened 2020-10-13 12:46 UTC by ArpinFidel

helper function for forming redis key

2020-10-14 02:04 UTC, heggies requested changes

2020-10-14 02:04 UTC, heggies commented on cache/cache.go
> +		key = os.Getenv("SERVICE_NAME")
kasih warn kalo `SERVICE_NAME` nya kosong

2020-10-14 03:51 UTC, heggies approved these changes

2020-10-15 08:25 UTC, yafetzz approved these changes

2020-10-15 08:25 UTC, merged