[go-utils/pagination] Granularized  pagination functionality & add total page
forkyid/go-utils pull request #36
Opened 2020-12-18 04:49 UTC by yohanesmichael72

2020-12-18 04:55 UTC, Amnestia approved these changes

2020-12-18 18:34 UTC, yohanesmichael72 commented
@yafetzz @agusID

2020-12-22 06:31 UTC, agusID requested changes
please change `Total` to `TotalData` to define how many data in the database.

2020-12-22 06:31 UTC, agusID commented on pagination/pagination.go
> +		p.Limit = p.Total
```suggestion
	if p.TotalData > 0 && p.TotalData < p.Limit {
		p.Limit = p.TotalData
```

2020-12-22 06:31 UTC, agusID commented on pagination/pagination.go
> +	p.TotalPage = int(math.Ceil(float64(p.Total) / float64(p.Limit)))
```suggestion
	p.TotalPage = int(math.Ceil(float64(p.TotalData) / float64(p.Limit)))
```

2020-12-22 13:33 UTC, yohanesmichael72 commented on pagination/pagination.go
> +	p.TotalPage = int(math.Ceil(float64(p.Total) / float64(p.Limit)))
updated

2020-12-22 13:34 UTC, yohanesmichael72 commented on pagination/pagination.go
> +		p.Limit = p.Total
updated

2020-12-22 13:36 UTC, yohanesmichael72 commented
> please change `Total` to `TotalData` to define how many data in the database.

updated

2020-12-22 13:41 UTC, yafetzz approved these changes

2020-12-23 03:48 UTC, agusID approved these changes

2020-12-23 03:56 UTC, merged