[COREAPI-285] Add Status Locked response struct
forkyid/go-utils pull request #55
Opened 2021-07-07 08:28 UTC by Zeltren0

## Description

> Please add your task in ClickUp here.

Task: [COREAPI-285](https://app.clickup.com/t/3857515/COREAPI-285)

## What's new?

> Please add if you added new improvement
- Add error 423 Lock Response to response struct

2021-07-07 08:30 UTC, ahtuz requested changes

2021-07-07 08:30 UTC, ahtuz commented on v1/rest/responsestruct.go
> +	Error string `json:"error" example:"Status Locked"`
432 message `Locked` saja
```suggestion
	Error string `json:"error" example:"Locked"`
```

2021-07-07 09:19 UTC, heggies approved these changes

2021-07-07 09:31 UTC, ahtuz approved these changes

2021-07-07 12:50 UTC, yafetzz approved these changes

2021-07-08 02:14 UTC, christyyy-a requested changes

2021-07-08 02:14 UTC, christyyy-a commented on v1/rest/responsestruct.go
> +	message
```suggestion
```

2021-07-08 02:39 UTC, christyyy-a approved these changes

2021-07-08 05:11 UTC, yafetzz approved these changes

2021-07-08 05:57 UTC, merged