[AI - 52] RabbitMQ Publisher in REST for Logging
forkyid/go-utils pull request #56
Opened 2021-07-07 12:34 UTC by wilhart

### Description

> Please add your task in ClickUp here.

Task: [AI-52](https://app.clickup.com/t/3857515/AI-52)

### What's New?

> Please add if you added new improvement

- Fix Error Read Body on `PublishLog`

2021-07-07 12:39 UTC, heggies requested changes

2021-07-07 12:39 UTC, heggies commented on v1/rest/rest.go
>  	go PublishLog(context, status, payload, msg[0])
```suggestion
	var copied gin.Context = *context
	go PublishLog(&copied, status, payload, msg[0])
```

2021-07-07 12:39 UTC, heggies commented on v1/rest/rest.go
>  	go PublishLog(context, status, nil, msg[0])
```suggestion
	var copied gin.Context = *context
	go PublishLog(&copied, status, nil, msg[0])
```

2021-07-07 23:04 UTC, heggies approved these changes

2021-07-08 01:54 UTC, ahtuz approved these changes

2021-07-08 02:42 UTC, christyyy-a approved these changes

2021-07-08 10:56 UTC, yafetzz approved these changes

2021-07-08 11:00 UTC, agusID approved these changes

2021-07-08 11:00 UTC, merged