[GIF-769] Add suspend checking on middeware/auth
forkyid/go-utils pull request #57
Opened 2021-07-12 03:59 UTC by arfaghif

## Description

> Please add your task in ClickUp here.

Task: [GIF-769](https://app.clickup.com/t/3857515/GIF-769)

## What's new?

> Please add if you added new improvement

- Add isSuspended function. This function is used for suspended checking for an service

2021-07-12 04:09 UTC, heggies requested changes

2021-07-12 04:09 UTC, heggies commented on v1/middleware/auth.go
> +func isSuspended(ctx *gin.Context, service string) gin.HandlerFunc {
```suggestion
func IsSuspended(feature string) gin.HandlerFunc {
```
huruf depan functionnya dibuat uppercase biar public. lalu ctx gaperlu dijadiin param

2021-07-12 04:09 UTC, heggies commented on v1/middleware/auth.go
> +		}
```suggestion
		client, _ := jwt.ExtractClient(ctx.GetHeader("Authorization"))
```
ini bisa dihapus aja, pengecekan authorization bisa lewat `middleware.Auth()`

2021-07-12 04:09 UTC, heggies commented on v1/middleware/auth.go
> +				logger.Log("failed on getting ttl from redis: " + err.Error())
```suggestion
				log.Println("failed on getting ttl from redis: " + err.Error())
```

2021-07-12 04:20 UTC, christyyy-a requested changes

2021-07-12 04:20 UTC, christyyy-a commented on v1/middleware/auth.go
> +func isSuspended(feature string) gin.HandlerFunc {
dibuat public function

2021-07-12 04:22 UTC, ahtuz requested changes

2021-07-12 04:22 UTC, ahtuz commented on v1/middleware/auth.go
> +					"until": time.Now().Add(time.Second * time.Duration(ttl)).Format("2006-01-02T15:04:05.999Z"),
```suggestion
					"until": time.Now().Add(time.Second * time.Duration(ttl)).Format(time.RFC3339),
```
seingatku di golang ada package time yg balikin format RFC3339 yg dipake di code ini.
jadi mungkin boleh diubah pake `const` RFC3339 saja daripada menggunakan string date.
atau mungkin ada alasan lain? btw, kalo diubah, minta tolong dicek juga ya jalan atau ngga codenya.

![image](https://user-images.githubusercontent.com/33178140/125230447-fb456180-e302-11eb-9a5a-ac2489c31e44.png)
https://golang.org/pkg/time/

2021-07-12 04:43 UTC, heggies approved these changes

2021-07-12 05:06 UTC, ahtuz commented on v1/middleware/auth.go
> +					"until": time.Now().Add(time.Second * time.Duration(ttl)).Format("2006-01-02T15:04:05.999Z"),
kalo menurut @heggies , @agusID . @christyyy-a , @agusID gimana?
harusnya `RFC3339 = "2006-01-02T15:04:05Z07:00" = "2006-01-02T15:04:05.999Z"` kan?

![image](https://user-images.githubusercontent.com/33178140/125233791-86c1f100-e309-11eb-80ab-b78bd3d0d401.png)
https://stackoverflow.com/questions/32592458/why-cant-go-parse-the-time-represented-by-the-provided-formats

2021-07-12 05:08 UTC, christyyy-a approved these changes

2021-07-12 05:25 UTC, ahtuz approved these changes

2021-07-13 03:22 UTC, yafetzz approved these changes

2021-07-13 10:39 UTC, agusID approved these changes

2021-07-13 10:39 UTC, merged