[COREAPI-355] request bind helper
forkyid/go-utils pull request #61
Opened 2021-08-09 16:11 UTC by heggies

## Description

> Please add your task in ClickUp here.

Task: [COREAPI-355](https://app.clickup.com/t/3857515/COREAPI-355)

## What's new?

> Please add if you added new improvement
- request bind helper (json, urlencoded, form-data, multipart/form-data)
- minor refactor on `PublishLog()`

plz wait imma write some how to use

2021-08-10 02:42 UTC, ahtuz requested changes

2021-08-10 02:42 UTC, ahtuz commented on v1/rest/bind.go
> +// 	return error
@heggies @christyyy-a jadi skrg kita ketentuan godoc kasih tab 1x kah utk params & return nya?

2021-08-10 02:56 UTC, heggies commented on v1/rest/bind.go
> +// 	return error
biar beda line aja sih 
![image](https://user-images.githubusercontent.com/13652659/128801355-26da4e4a-3dc3-455c-b438-cd70e659f633.png)

kalo gak dikasih tab 
![image](https://user-images.githubusercontent.com/13652659/128801409-8546e185-b9aa-4d7d-88f3-1b0fd7576d3b.png)

2021-08-10 03:02 UTC, ahtuz commented on v1/rest/bind.go
> +// 	return error
iya, apa kita mulai sekarang pake tab gitu aja utk godoc?

2021-08-10 04:24 UTC, yafetzz requested changes

2021-08-10 04:24 UTC, yafetzz commented on v1/rest/rest.go
> +	if contentType == "application/json" && len(requestBody) > 1 {
```suggestion
	if contentType == "application/json" && len(requestBody) > 0 {
```

pak titip tolong ubah dong

2021-08-10 04:30 UTC, yafetzz approved these changes

2021-08-10 04:32 UTC, heggies commented on v1/rest/bind.go
> +// 	return error
dari aku si yes, bagaimana ci @christyyy-a

2021-08-10 08:16 UTC, ahtuz approved these changes
dah oke sih

2021-08-10 09:28 UTC, christyyy-a approved these changes

2021-08-10 09:28 UTC, christyyy-a commented on v1/rest/bind.go
> +// 	return error
ini sepertinya sudah di bahas di clickup, oke kalo dari saya

2021-08-16 06:58 UTC, agusID approved these changes

2021-08-16 07:02 UTC, agusID approved these changes

2021-08-16 07:02 UTC, merged