[COREAPI-396] remove restid-related helper, jwt generator, refactor logger
forkyid/go-utils pull request #62
Opened 2021-08-13 06:20 UTC by heggies

## Description

> Please add your task in ClickUp here.

Task: [COREAPI-396](https://app.clickup.com/t/3857515/COREAPI-396)

## What's new?

> Please add if you added new improvement
- remove `restid`-related helper
- remove jwt generator
- refactor logger, stack trace
- fix #50

2021-08-13 07:28 UTC, ahtuz requested changes

2021-08-13 07:28 UTC, ahtuz commented on v1/logger/logger.go
> +// 	@errMsg: string
private func perlu godoc?
@heggies @christyyy-a

2021-08-13 07:30 UTC, heggies commented on v1/logger/logger.go
> +// 	@errMsg: string
bagaimana @christyyy-a 
saya ngikutin christy

2021-08-13 14:02 UTC, christyyy-a commented on v1/logger/logger.go
> +// 	@errMsg: string
![image](https://user-images.githubusercontent.com/51283152/129368813-f2c1fe43-4a86-4f19-8683-ecc0c142fea1.png)
semoga menjawab

2021-08-13 14:16 UTC, christyyy-a approved these changes

2021-08-16 02:51 UTC, ahtuz approved these changes

2021-08-16 02:52 UTC, ahtuz commented on v1/logger/logger.go
> +// 	@errMsg: string
jadi jawabnya apa ini WKWKK
pakein aja?

2021-08-16 07:32 UTC, agusID commented on v1/logger/logger.go
> +// 	@errMsg: string
@heggies , ini dipakai aja, GTG

2021-08-16 07:32 UTC, agusID approved these changes

2021-08-16 07:45 UTC, yafetzz approved these changes

2021-08-16 07:46 UTC, merged