[DVM-8260] Handle Server Down Time
forkyid/go-utils pull request #94
Opened 2022-08-30 13:05 UTC by winsonsutanto10

## Description

> Please add your task in ClickUp here.

Task:  [DVM-8260](https://app.clickup.com/t/3857515/DVM-8260)
## What's new?

> Please add if you added new improvement

add CheckFeatureFlagStatus in middleware

2022-08-30 13:44 UTC, ahtuz requested changes

2022-08-30 13:44 UTC, ahtuz commented on v1/middleware/featureflagstatus.go
> +func (mid *Middleware) CheckFeatureFlagStatus(key string) gin.HandlerFunc {
titip add penjelasan func ya

2022-08-30 13:44 UTC, ahtuz commented on v1/middleware/featureflagstatus.go
> +	err = errors.Wrap(err, "unmarshall data")
```suggestion
	err = errors.Wrap(err, "unmarshal data")
```

2022-08-30 13:44 UTC, ahtuz commented on v1/middleware/featureflagstatus.go
> +func getFeatureFlagStatus(key string) (status FeatureFlagStatus, err error) {
titip add penjelasan func

2022-08-30 14:35 UTC, winsonsutanto10 commented on v1/middleware/interface.go
> +	CheckFeatureFlagStatus(key string)
ada disini contextnya
![image](https://user-images.githubusercontent.com/108509628/187465176-f46268b5-549c-4f15-acd4-de59adbdaea0.png)

2022-08-31 05:13 UTC, ahtuz commented
RC pindah ke CU ya

2022-08-31 08:23 UTC, liemmatthew approved these changes

2022-08-31 08:40 UTC, asianjack19 approved these changes

2022-08-31 09:03 UTC, ahtuz requested changes
cek CU

2022-08-31 09:07 UTC, ahtuz requested changes
rc lagi ngebug gak keluar

2022-08-31 09:51 UTC, ahtuz approved these changes

2022-09-20 09:31 UTC, ahtuz requested changes
.

2022-09-20 10:06 UTC, ahtuz approved these changes

2022-09-21 03:40 UTC, christyyy-a approved these changes

2022-09-21 05:11 UTC, yafetzz approved these changes

2022-09-21 05:26 UTC, merged